method: bayes

metric:
  name : 'iou'
  goal: 'maximize'

parameters:
  category:
    value: 15

  agg:
    values: ['mean_var', 'lab_mean_var', 'lab_mean_var_hist']

  n_segments:
    distribution: int_uniform
    min: 100
    max: 500

  compactness:
    distribution: int_uniform
    min: 10
    max: 50

  model:
    values: ['rdf', 'density', 'mlp']

  max_iter:
    value: 100
  
  beta:
    distribution: 'uniform'
    min: 0.5
    max: 2
  
  sigma:
    distribution: 'uniform'
    min: 50
    max: 200
  
  